[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["python -m pip install# Force Rebuild Finance 2026-02-13 V3.2
"]

[start]
cmd = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
