[phases.setup]
nixPkgs = ["python3", "postgresql"]
# Force Rebuild 2026-02-12


[phases.build]
cmds = ["pip install -r backend/requirements.txt"]

[start]
cmd = "cd backend/services/accounts && python main.py"
